<<<<<<< Updated upstream
import type { Metadata } from "next";
// @ts-expect-error — named font exports are generated by the Next.js TS plugin at dev time.
// The imports are valid at runtime; see next/font/google docs.
import { Inter, DM_Serif_Display } from "next/font/google";
=======
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
>>>>>>> Stashed changes
import "./globals.css";
import BottomNav from "./components/BottomNav";
import TopNav from "./components/TopNav";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const dmSerif = DM_Serif_Display({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
<<<<<<< Updated upstream
  title: "SmartFlow — Smart Event Crowd Management",
  description:
    "Real-time intelligence that helps event teams monitor crowds, predict congestion, and coordinate the response before small bottlenecks become operational problems.",
=======
  title: "Venuro — Event Companion",
  description:
    "Venuro helps event attendees navigate zones, crowds and facilities, with live updates.",
};

export const viewport: Viewport = {
  themeColor: "#2563eb",
  width: "device-width",
  initialScale: 1,
>>>>>>> Stashed changes
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${dmSerif.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        {/*
          App shell (mobile-first).
          - Phone: centered column with a fixed bottom nav.
          - Desktop (lg+): a centered top nav bar instead of the bottom bar,
            with the content kept in a centered column.
        */}
        <TopNav />
        <div className="mx-auto flex min-h-dvh w-full max-w-md flex-1 flex-col lg:my-0 lg:min-h-0 lg:max-w-3xl lg:flex-1">
          <main className="flex-1 pb-28 lg:pb-12">{children}</main>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
