import type { Metadata } from "next";
// @ts-expect-error — named font exports are generated by the Next.js TS plugin at dev time.
// The imports are valid at runtime; see next/font/google docs.
import { Inter, DM_Serif_Display } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const dmSerif = DM_Serif_Display({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "SmartFlow — Smart Event Crowd Management",
  description:
    "Real-time intelligence that helps event teams monitor crowds, predict congestion, and coordinate the response before small bottlenecks become operational problems.",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${dmSerif.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
